# Étape 1 : build Node
FROM node:20-alpine AS build
WORKDIR /app

# On copie le package.json et package-lock.json
COPY frontend/app/package*.json ./
RUN npm ci

# On copie tout le reste du frontend
COPY frontend/app/ ./
RUN npm run build

# Étape 2 : nginx
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
